# Generated by Django 4.2.7 on 2025-05-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('nutrition_facts', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
