# Generated by Django 4.2.7 on 2025-05-12 12:08

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_enable_trigram'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='products_pr_search__98d711_gin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='search_vector',
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='product_name_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['brand'], name='product_brand_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['category'], name='product_category_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
